#! /usr/bin/env python
from rabies.preprocess_pkg.utils import run_command
command = "rabies preprocess debug_data/ out_test --debug --anat_bias_cor_method disable --bold_bias_cor_method disable --coreg_script null_nonlin --template_reg_script null_nonlin"
rc = run_command(command)
