name: Build and Attach Apptainer Image from Docker URL to Release
on:
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name (e.g., 0.5.0)'
        required: true
        type: string

jobs:
  build-and-attach:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install Apptainer
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository -y ppa:apptainer/ppa
          sudo apt-get install -y apptainer
      
      - name: Get release version
        id: get_version
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "VERSION=${{ inputs.tag_name }}" >> "$GITHUB_OUTPUT"
          else
            echo "VERSION=${GITHUB_REF#refs/tags/}" >> "$GITHUB_OUTPUT"
          fi
      
      - name: Build Apptainer image from Docker URL
        run: |
          REPO_LOWERCASE=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          VERSION=${{ steps.get_version.outputs.VERSION }}
          sudo apptainer build "app-${VERSION}.sif" "docker://ghcr.io/${REPO_LOWERCASE}:${VERSION}"
      
      - name: Upload image to release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          files: app-${{ steps.get_version.outputs.VERSION }}.sif
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
