name: PR Workflow - test that dockerfile will build on a PR to master

on:
  workflow_dispatch:
    inputs:
        run_tests:
          description: "No cache for build?"
          required: false
          default: "false"
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and tag image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          tags: rabies:pr-${{ github.event.pull_request.number || 'manual' }}
          no-cache: ${{ github.event.inputs.run_tests == 'true' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
